### ISSUE TITLE
error with pokemon bot

### ISSUE THREAD

**Issue by Tenacity2s** [kwsch/SysBot.NET#151]
[15:25:13] - 192.168.1.23: Bot has crashed!
[15:25:13] - 192.168.1.23: Aggregate message: One or more errors occurred.
[15:25:13] - 192.168.1.23: Inner message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [::ffff:192.168.1.23]:6000
[15:25:13] - 192.168.1.23: Inner stacktrace:    at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at SysBot.Base.SwitchSocketAsync.Connect()
   at SysBot.Base.RoutineExecutor`1.<RunAsync>d__14.MoveNext()
dont know what i did wrong and why it isnt connecting

**Comment by Lusamine** [comment]
Go over the Wiki > Troubleshooting Connection Errors. It's almost always one of those things on there.
