### ISSUE TITLE
unable to connect to switch 

### ISSUE THREAD

**Issue by gingerx9-91** [kwsch/SysBot.NET#187]
Hey, I've followed every tutorial you have on here but my switch is declining the request; 

ive joined the discord but i don't have access to the channels to post images and get help there.

perhaps you will be able to solve this issue for me? 

many thanks

**Comment by gingerx9-91** [comment]
2023-10-14 23:56:27.5229|INFO|SysBot.Base.LogUtil|Form Starting all bots...
2023-10-14 23:56:27.5229|INFO|SysBot.Base.LogUtil|Echo All bots have been issued a command to Start.
2023-10-14 23:56:27.5229|INFO|SysBot.Base.LogUtil|192.168.0.183 Connecting to device...
2023-10-14 23:56:30.0204|ERROR|SysBot.Base.LogUtil|192.168.0.183 Bot has crashed!
2023-10-14 23:56:30.0204|ERROR|SysBot.Base.LogUtil|192.168.0.183 Aggregate message: One or more errors occurred. (No connection could be made because the target machine actively refused it. [::ffff:192.168.0.183]:6000)
2023-10-14 23:56:30.0227|ERROR|SysBot.Base.LogUtil|192.168.0.183 Inner message: No connection could be made because the target machine actively refused it. [::ffff:192.168.0.183]:6000
2023-10-14 23:56:30.0227|ERROR|SysBot.Base.LogUtil|192.168.0.183 Inner stacktrace:    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at SysBot.Base.SwitchSocketAsync.Connect()
   at SysBot.Base.RoutineExecutor`1.RunAsync(CancellationToken token)

**Comment by Lusamine** [comment]
GitHub issues are for problems with the program, not failure to read the documentation. If you don't know how to access the channel, you haven't read the wiki. There's a whole page for how to troubleshoot this error.
