### ISSUE TITLE
Sysbot and Switch Connection Issue

### ISSUE THREAD

**Issue by jsmi1182** [kwsch/SysBot.NET#99]
I have followed the wiki instructions to the best of my ability. I do have CFW and did install sysbot-base onto the root of my SD Card. When I press start, however, the bot crashes and the log says:

2020-11-24 12:18:37.3183|INFO|SysBot.Base.LogUtil|192.168.1.207: SwitchConnectionAsync Connecting to device...
2020-11-24 12:18:37.3781|INFO|SysBot.Base.LogUtil|SysCord: [    Info] Discord: Discord.Net v2.2.0 (API v6) 
2020-11-24 12:18:37.7667|INFO|SysBot.Base.LogUtil|SysCord: [    Info] Gateway: Connecting 
2020-11-24 12:18:38.1056|INFO|SysBot.Base.LogUtil|SysCord: [    Info] Gateway: Connected 
2020-11-24 12:18:38.5913|INFO|SysBot.Base.LogUtil|SysCord: [    Info] Gateway: Ready 
2020-11-24 12:18:39.4131|ERROR|SysBot.Base.LogUtil|IP Address goes here: SwitchConnectionAsync Bot has crashed!
2020-11-24 12:18:39.4131|ERROR|SysBot.Base.LogUtil|IP Address goes here: SwitchConnectionAsync Aggregate message:One or more errors occurred.
2020-11-24 12:18:39.4131|ERROR|SysBot.Base.LogUtil|IP Address goes here: SwitchConnectionAsync Inner message:No connection could be made because the target machine actively refused it [::ffff: IP Address goes here ]:6000
2020-11-24 12:18:39.4271|ERROR|SysBot.Base.LogUtil| IP Address goes here: SwitchConnectionAsync Inner stacktrace:   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at SysBot.Base.SwitchConnectionAsync.Connect()
   at SysBot.Base.SwitchRoutineExecutor`1.<RunAsync>d__13.MoveNext()

Does anyone know how to fix this? Or is this simply my own internet connection issues?

**Comment by Lusamine** [comment]
This is not an issue with the program.  There is something wrong with your connection configuration. All we can do is tell you the most likely causes, which are all on the wiki under Troubleshooting.

**Comment by enlighten1self** [comment]
> I have followed the wiki instructions to the best of my ability. I do have CFW and did install sysbot-base onto the root of my SD Card. When I press start, however, the bot crashes and the log says:
> 
> 
> 
> 2020-11-24 12:18:37.3183|INFO|SysBot.Base.LogUtil|192.168.1.207: SwitchConnectionAsync Connecting to device...
> 
> 2020-11-24 12:18:37.3781|INFO|SysBot.Base.LogUtil|SysCord: [    Info] Discord: Discord.Net v2.2.0 (API v6) 
> 
> 2020-11-24 12:18:37.7667|INFO|SysBot.Base.LogUtil|SysCord: [    Info] Gateway: Connecting 
> 
> 2020-11-24 12:18:38.1056|INFO|SysBot.Base.LogUtil|SysCord: [    Info] Gateway: Connected 
> 
> 2020-11-24 12:18:38.5913|INFO|SysBot.Base.LogUtil|SysCord: [    Info] Gateway: Ready 
> 
> 2020-11-24 12:18:39.4131|ERROR|SysBot.Base.LogUtil|IP Address goes here: SwitchConnectionAsync Bot has crashed!
> 
> 2020-11-24 12:18:39.4131|ERROR|SysBot.Base.LogUtil|IP Address goes here: SwitchConnectionAsync Aggregate message:One or more errors occurred.
> 
> 2020-11-24 12:18:39.4131|ERROR|SysBot.Base.LogUtil|IP Address goes here: SwitchConnectionAsync Inner message:No connection could be made because the target machine actively refused it [::ffff: IP Address goes here ]:6000
> 
> 2020-11-24 12:18:39.4271|ERROR|SysBot.Base.LogUtil| IP Address goes here: SwitchConnectionAsync Inner stacktrace:   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
> 
>    at System.Net.Sockets.Socket.Connect(String host, Int32 port)
> 
>    at SysBot.Base.SwitchConnectionAsync.Connect()
> 
>    at SysBot.Base.SwitchRoutineExecutor`1.<RunAsync>d__13.MoveNext()
> 
> 
> 
> Does anyone know how to fix this? Or is this simply my own internet connection issues?
> 
> 

I think I had this issue before and turned off async setting in the hub module for discord integration. I hope you fixed this already but I also urge you to read the wiki many times, as every time I go back I learn something new.
